server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gmall_product
  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
  zipkin:
    base-url: http://127.0.0.1:9411
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest